
- hosts: kubenodes
  remote_user: "{{ user }}"
  become: yes
  vars: 
    src_dir: "{{ playbook_dir }}"
  vars_files:
    - "{{ src_dir }}/conf/cluster.yml"
  tasks:
    - name: "Add Crontab"
      cron:
        name: "Uptimerobot heartbeat"
        minute: "*/1"
        hour: "*"
        job: "wget --spider \"{{ heartbeaturl }}\" >/dev/null 2>&1" 
